name: Daily File

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

jobs:
  update-file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Download file from codepen
      run: |
        ./download.sh
    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'actions@github.com'
        git pull origin main --rebase --force
        git add .
        if ! git diff-index --quiet HEAD; then
          git commit -m 'Add new file'
          git push
        else
          echo "No changes to commit."
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
